# Generated by Django 3.2.11 on 2022-02-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_handler', '0002_rename_historymanager_posthistorymanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posthistorymanager',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='posthistorymanager',
            old_name='created',
            new_name='created_on',
        ),
    ]
