# Generated by Django 3.2.11 on 2022-02-04 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media_handler', '0003_auto_20220202_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='watch_later',
        ),
        migrations.AddField(
            model_name='post',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='watchlist_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
